//images

export default {
    background: require("../assets/Images/background.png"),
    splashImg: require("../assets/Images/splashImg.png"),
    logo: require("../assets/Images/logo.png"),
    layer_1: require("../assets/Images/layer_1.png"),
    layer_2: require("../assets/Images/layer_2.png"),
    layer_3: require("../assets/Images/layer_3.png"),
    layer_4: require("../assets/Images/layer_4.png"),
    layer_5: require("../assets/Images/layer_5.png"),
    last: require("../assets/Images/last.png"),
    linkdin: require("../assets/Images/linkdin.png"),
    facebook: require("../assets/Images/facebook.png"),
    apple: require("../assets/Images/apple.png"),
    password: require("../assets/Images/password.png"),
    unshow: require("../assets/Images/unshow.png"),
    email: require("../assets/Images/email.png"),
    checkActive: require("../assets/Images/checkActive.png"),
    uncheck: require("../assets/Images/uncheck.png"),
    back: require("../assets/Images/back.png"),
    blankPic: require("../assets/Images/blankPic.png"),
    edit: require("../assets/Images/edit.png"),
    workProfile: require("../assets/Images/workProfile.png"),
    right: require("../assets/Images/right.png"),
    profilePic: require("../assets/Images/profilePic.png"),
    LinkedInLogo: require("../assets/Images/LinkedInLogo.png"),
    camera: require("../assets/Images/camera.png"),
    upload: require("../assets/Images/upload.png"),
    portal: require("../assets/Images/portal.png"),
    editProfile: require("../assets/Images/editProfile.png"),
    object: require("../assets/Images/object.png"),
    lightCamera: require("../assets/Images/lightCamera.png"),
    share: require("../assets/Images/share.png"),
    message: require("../assets/Images/message.png"),
    setting: require("../assets/Images/setting.png"),
    bell: require("../assets/Images/bell.png"),
    companyLogo: require("../assets/Images/companyLogo.png"),
    calendar: require("../assets/Images/calendar.png"),
    uploadImage: require("../assets/uploadImage.png"),
    search: require("../assets/Images/search.png"),
    lines: require("../assets/Images/lines.png"),
    ask: require("../assets/Images/ask.png"),
    give: require("../assets/Images/give.png"),
    bellon: require("../assets/Images/bellon.png"),
    pofileoff: require("../assets/Images/pofileoff.png"),
    postpic: require("../assets/Images/postpic.png"),
    like: require("../assets/Images/like.png"),
    comment: require("../assets/Images/comment.png"),
    share2: require("../assets/Images/share2.png"),
    threeline:require("../assets/Images/threeline.png"),
    askBar2:require("../assets/Images/askBar2.png"),
    giveBar2:require("../assets/Images/giveBar2.png"),
    cross:require("../assets/Images/cross.png"),
    backblack:require("../assets/Images/backblack.png"),
    down:require("../assets/Images/down.png"),
    attched:require("../assets/Images/attched.png"),
    loaction:require("../assets/Images/loaction.png"),
    man2:require("../assets/Images/man2.png"),
    mens:require("../assets/Images/mens.png"),
    gridspic:require("../assets/Images/gridspic.png"),
    search2:require("../assets/Images/search2.png"),
    business:require("../assets/Images/business.png"),
    edu:require("../assets/Images/edu.png"),
    freelance:require("../assets/Images/freelance.png"),
    search3:require("../assets/Images/search3.png"),
    groupPlus:require("../assets/Images/groupPlus.png"),
    leftblue:require("../assets/Images/leftblue.png"),
    rightblue:require("../assets/Images/rightblue.png"),
    ImagePlace:require("../assets/Images/ImagePlace.png"),
    porfile:require("../assets/Images/porfile.png"),
    pic2:require("../assets/Images/pic2.png"),
    dots1:require("../assets/Images/dots1.png"),
    clock:require("../assets/Images/clock.png"),
    leave:require("../assets/Images/leave.png"),
    mute:require("../assets/Images/mute.png"),
    Group2:require("../assets/Images/Group2.png"),
    redCross:require("../assets/Images/redCross.png"),
    checkd:require("../assets/Images/checkd.png"),
    leftred:require("../assets/Images/leftred.png"),
    redleft:require("../assets/Images/redleft.png"),
    whiteG:require("../assets/Images/whiteG.png"),
    background2:require("../assets/Images/background2.png"),
    center_Icon: require("../assets/center_Icon.png"),
    backAero: require("../assets/Images/backAero.png"),
    paymentImg: require("../assets/Images/paymentImg.png"),
    stripeImg: require("../assets/Images/stripeImg.png"),
    rightImg: require("../assets/Images/rightImg.png"),
    Mastercard: require("../assets/Images/Mastercard.png"),
    PaySuccessImg: require("../assets/Images/PaySuccessImg.png"),
    forwordAero: require("../assets/Images/forwordAero.png"),
    paymentFailImg: require("../assets/Images/paymentFailImg.png"),
    gridImg: require("../assets/Images/gridImg.png"),
    micgreen:require("../assets/Images/micgreen.png"),
    micRed:require("../assets/Images/micRed.png"),
    chat:require("../assets/Images/chat.png"),
    whiteBack:require("../assets/Images/whiteBack.png"),
    edit1:require("../assets/Images/edit1.png"),
    calendar1:require("../assets/Images/calendar1.png"),
    clock2:require("../assets/Images/clock2.png"),
    ask1:require("../assets/Images/ask1.png"),
    unLike:require("../assets/Images/unLike.png"),
    voiceblack:require("../assets/Images/voiceblack.png"),
    cleander3:require("../assets/Images/cleander3.png"),
    // gridImg: require("../assets/Images/gridImg.png"),
    // gridImg: require("../assets/Images/gridImg.png"),
    // gridImg: require("../assets/Images/gridImg.png"),
    // gridImg: require("../assets/Images/gridImg.png"),
    // gridImg: require("../assets/Images/gridImg.png"),
    // gridImg: require("../assets/Images/gridImg.png"),
    center_Icon: require("../assets/center_Icon.png"),
    eye:require("../assets/Images/eye.png")
  }
  